### ISSUE TITLE
Add GitHub pages and documentation generation

### ISSUE THREAD

**Issue by mavnn** [fsprojects/FSharp.TypeProviders.SDK#1]
Check out FSharp.Data or https://github.com/forki/DynamicsNAVProvider for ways this could work.

If you're interested in helping out with this, ping me and I'll give you the relevant permissions for creating the gh-pages.

**Comment by eriawan** [comment]
@mavnn Could you elaborate a bit more on what kind of documentation generation? As far as I can see, the documentation of DynamicsNAVProvider is in the forms of comment.
For example: https://github.com/fsprojects/DynamicsNAVProvider/blob/master/docs/content/index.fsx
and currently I don't know how to display or the convention to write the document.

**Comment by sergey-tihon** [comment]
@eriawan This is a format of [F# Formatting: Literate programming](http://tpetricek.github.io/FSharp.Formatting/literate.html)

imho, the easiest way to start it to create new project based on https://github.com/fsprojects/ProjectScaffold and read `build.fsx` and then `generate.fsx` (https://github.com/fsprojects/DynamicsNAVProvider/blob/master/docs/tools/generate.fsx) and you will see how script combine output of FSharp.Formatting and Razor page template.

The other way is to look at `http://fable.io` or `http://fsprojects.github.io/SwaggerProvider/` - both use `FSharp.Formatting`, `DotLiquid` and `Suave` to create docs.

**Comment by eriawan** [comment]
@sergey-tihon thanks! I'll try to learn and use it for now.

I didn't know this before! It's actually a good library to create docs :)
OK, I'll learn to use this. After that, I'll try to continue to discuss the next step of the doc with you

**Comment by dsyme** [comment]
fsdocs has been added
