### ISSUE TITLE
Question re: generative providers and testing

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.TypeProviders.SDK#140]
### Description

I'm working on testing out the new context-aware changes on the SwaggerProvider [PR here](https://github.com/fsprojects/SwaggerProvider/pull/88), and wanted to make sure I was doing things correctly.

I ran into a small problem with the way the SwaggerProvider does its testing. I need to be able to create a testing TypeProviderConfig, which I'd like to do with `ProvidedTypesTesting.Testing.MakeSimulatedTypeProviderConfig`, but that whole module is marked `internal` so it's not available across the module boundary.

Is there a more-supported way to test TP generation?

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone the SwaggerProvider PR linked above
2. Run `build.cmd` or `build.sh`
3. See the compilation failure in `SwaggerProvider\tests\SwaggerProvider.Tests\Schema.Parser.Tests.fs`.

### Expected behavior

I have some mechanism to create a TypeProviderConfig

### Actual behavior

I can't without removing the `internal` scope from the module .

### Known workarounds

Remove the `internal` scope from the module .

### Related information 

* Any OS
* master@130750141e9033f2f6f82368745a18fafe98d305
* .NET Runtime 4.7

**Comment by sergey-tihon** [comment]
The PR mentioned in this PR fails with error (when compiling the project that uses TP)

> error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: The operation 'Namespace' on item 'Pet[]' should not be called on provided type, member or parameter [/Users/sergey/github/SwaggerProvider/tests/SwaggerProvider.ProviderTests/SwaggerProvider.ProviderTests.fsproj]

this also looks like an issue of SDK.

Repro steps are the same

**Comment by dsyme** [comment]
@baronfel Can use use InternalsVisibleTo?

**Comment by dsyme** [comment]
@baronfel Did using InternalsVisibleTo help?

**Comment by sergey-tihon** [comment]
Since we rolled back to initial API that does not use context - https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/148#issuecomment-337322932

we do not really need it anymore. I did restore tests here - https://github.com/fsprojects/SwaggerProvider/pull/88/commits/30da54049b98bf7ffda240e4523cb8ebf8f4614c

@baronfel please reopen if i am wrong
