### ISSUE TITLE
Need newer nuget package published after having rename from FSharp.TypeProviders.StarterPack to FSharp.TypeProviders.SDK

### ISSUE THREAD

**Issue by eriawan** [fsprojects/FSharp.TypeProviders.SDK#141]
### Description

This repo and the subsequent F# project and nuspec has been updated with newer name. The old nuget still has the old name of FSharp.TypeProviders.StarterPack.
Current FSharp.TypeProviders.StarterPack on nuget is still has the old name: https://www.nuget.org/packages/FSharp.TypeProviders.StarterPack/

### Repro steps

Just look at the source in this repo, compile it and generate the nuget package.

### Expected behavior

Nuget site of FSharp.TypeProviders.StarterPack should be updated to FSharp.TypeProviders.SDK.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Maybe we need to publish new nuget with the newer name of FSharp.TypeProviders.SDK and update the info on the older page of FSharp.TypeProviders.StarterPack to use newer FSharp.TypeProviders.SDK package instead.

### Related information 

None.

**Comment by eriawan** [comment]
@ovatsus any plan to submit update to nuget? Or do you have to have stabilization release first?

**Comment by dsyme** [comment]
@eriawan We will stabilize. I'm actually tempted to remove the nuget package - perhaps in favour of a binary package

**Comment by eriawan** [comment]
@dsyme 
Thanks for the reply! Ok, I'll wait for the stable version. 

> I'm actually tempted to remove the nuget package - perhaps in favour of a binary package

binary package instead of nuget package? could you please elaborate?

**Comment by eriawan** [comment]
@dsyme 

any update or plan on this issue? please confirm...

**Comment by sergey-tihon** [comment]
I think that we should unlist of version of Starterpack from
FSharp.TypeProviders.StarterPac from nuget and say that paket-github file ref is the only supported way of mastering TPs.

@eriawan any cons?

**Comment by dsyme** [comment]
I agree.  @sergey-tihon Can you look after doing that?  thank you!

**Comment by sergey-tihon** [comment]
All versions of `FSharp.TypeProviders.StarterPack` are unlisted and it should not appear in NuGet search anymore

<img width="881" alt="nuget_gallery___fsharp_typeproviders_starterpack_2_1_0" src="https://user-images.githubusercontent.com/1197905/53618861-3943fe00-3bfe-11e9-85f6-5d2e230f7d18.png">

**Comment by eriawan** [comment]
@sergey-tihon 

> I think that we should unlist of version of Starterpack from
FSharp.TypeProviders.StarterPac from nuget and say that paket-github file ref is the only supported way of mastering TPs.
> @eriawan any cons?

No. I am glad that the package has been unlisted. 🙂 
So when we will have updated guidelines to use paket-github file ref? Is the guideline available now?

Thanks in advance.

**Comment by sergey-tihon** [comment]
> Is the guideline available now?

Yes, here it is, paket is part of official TP template
https://github.com/fsprojects/FSharp.TypeProviders.SDK#getting-started
