### ISSUE TITLE
Azure Storage TP Upgrade error

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.TypeProviders.SDK#147]
### Description
Using the latest version of `ProvidedTypes.fs`, I've updated the Azure TP in [this branch](https://github.com/fsprojects/AzureStorageTypeProvider/tree/cross-targeting). The main solution builds fine, but the Test project that references the TP does not work: 

```
C:\Users\Isaac\Source\Repos\AzureStorageTypeProvider\tests\IntegrationTests\TableUnitTests.fs(28,20): error FS3033: The type provider 'ProviderImplementation.AzureTypeProvider' reported an error in the context of provided type 'FSharp.Azure.StorageTypeProvider.AzureTypeProvider,accountName="DevStorageAccount"+Domain+optionalsEntity', member 'get_IsAnimal'. The error: generic parameter index our of range: 0 [C:\Users\Isaac\Source\Repos\AzureStorageTypeProvider\tests\IntegrationTests\IntegrationTests.fsproj]
```

However, I'm able to get it to work absolutely fine in a script - it appears that it's just in a compiled project that the issue appears. Note that the Test project is MSBuild 14, .NET 4.5.2, F#4.0.

It also compiles fine for the Blob and Queue provided types - it's something about the way we're creating Table entities that's causing the issue. My feeling is that the issue lies somewhere in the `TableEntityMemberFactory.setPropertiesForEntity` function (or functions called within).

### Repro steps

1. Download the Azure Type Provider repository.
2. Switch to the **cross-targeting** branch.
3. Run `build.cmd`. The FAKE script will fail whilst building the test project.

**Comment by isaacabraham** [comment]
I've updated to the latest version of the SDK. Different error message now:

```FS0193: FSC(0,0): The module/namespace 'FSharp.Azure.StorageTypeProvider.AzureTypeProvider,accountName="DevStorageAccount".Domain' from compilation unit 'FSharp.Azure.StorageTypeProvider' did not contain the namespace, module or type 'samplesContainer'```

It looks like the namespace is somehow not being attached to the provided types that are being created. However, the diff between this branch and the (working) master seems to suggest that nothing has changed in how they're being created. It's possible that how they've been created thus far has always been wrong but it was somehow working nonetheless, or that there's been a breaking change since the move to cross-targetting provider model.

**Comment by isaacabraham** [comment]
I've narrowed this down to something with `AddMembersDelayed()` on `ProvidedTypeDefinition`. If I change the call to `AddMembers`, the types and properties are correctly registered, but because of the nature of the Azure TP, this isn't really a viable option i.e. we wouldn't want to eagerly go through all containers and blobs in a storage to build the types and properties up.

**Comment by dsyme** [comment]
Ok, will take a look

**Comment by dsyme** [comment]
@isaacabraham WHich specific call to AddMembersDelayed/AddMembers did you change?  I see two calls to AddMembers in that branch

* https://github.com/fsprojects/AzureStorageTypeProvider/blob/cross-targeting/src/FSharp.Azure.StorageTypeProvider/AzureTypeProvider.fs#L62
* https://github.com/fsprojects/AzureStorageTypeProvider/blob/cross-targeting/src/FSharp.Azure.StorageTypeProvider/AzureTypeProvider.fs#L69

I assume you mean the second call?  Could you send me a link to the code as it is when it is failing?  Thanks

Also if you have a better callstack for the failure that would be great

**Comment by dsyme** [comment]
[This call](https://github.com/fsprojects/AzureStorageTypeProvider/blob/cross-targeting/src/FSharp.Azure.StorageTypeProvider/AzureTypeProvider.fs#L62) is dubious - it looks like you might be adding the same coreBlobTypes to multiple different static instantiations?  You should generate a new set of coreBlobTypes for each ApplyStaticParameters

I don't know if it's the problem though - it would depend if your test case is testing multiple different static parameters

We should add a failure if the same provided thing is added to multiple different parents.

**Comment by isaacabraham** [comment]
Sorry, I didn't do a great job of explaining. The call that fails on the TP is:

https://github.com/fsprojects/AzureStorageTypeProvider/blob/cross-targeting/src/FSharp.Azure.StorageTypeProvider/Blob/BlobMemberFactory.fs#L54

It all compiles, but at runtime the TP fails:

![image](https://user-images.githubusercontent.com/1781813/31902968-95536826-b81e-11e7-86ad-7040392f6a45.png)

The full error message is:

```
error FS0193: The module/namespace 'FSharp.Azure.StorageTypeProvider.AzureTypeProvider,accountName="UseDevelopmentStorage=true".Domain' from compilation unit 'FSharp.Azure.StorageTypeProvider' did not contain the namespace, module or type 'samplesContainer'
error FS1109: A reference to the type 'FSharp.Azure.StorageTypeProvider.AzureTypeProvider,accountName="UseDevelopmentStorage=true".Domain.samplesContainer' in assembly 'FSharp.Azure.StorageTypeProvider' was found, but the type could not be found in that assembly
```

I've tried changing this code locally to eagerly load in data (using `AddMembers` instead) and it worked.

**Comment by isaacabraham** [comment]
Good spot re: coreBlobTypes - I've noticed that as well. Indeed, I'm not sure that they need to be provided types at all. That'll be fixed in due course too.

**Comment by dsyme** [comment]
@isaacabraham This one looks a bit tricky and I'd like to get a repro to add to the SDK testing.

Is there any chance you could make a step-by-step repro that demonstrates the problem without any use of Azure storage etc?  i.e. just uses mock data and provided types?  I know that might be quite a bit of work.

I haven't yet spotted anything that could cause inconsistent translation when AddMembersDelayed is being used.  Uses of AddMembers and AddMembersDelayed at any point except immediately after the creation of a provided type might plausibly cause problems, but I've not yet spotted anything where converting AddMembers to AddMembersDelayed would cause problems.

**Comment by isaacabraham** [comment]
I've created a simpler repro here with a comment in the project where the problem happens.

https://github.com/isaacabraham/sampletp

**Comment by dsyme** [comment]
Here's a slightly reduced repro: https://gist.github.com/dsyme/d774bb16055dd8e3ec8df260c13c5700

with usage 
```
#r @"bin\Debug\SampleTP.dll"

type P = Sample.SampleTypeProvider<"a">

printfn "%A" P.StaticProperty.A
```

**Comment by dsyme** [comment]
@isaacabraham Fixed by #167.  Thanks for making the standalone repro - it means we now have this under test

**Comment by isaacabraham** [comment]
Seems to all build :-) Does this mean the TP is theoretically compatible with .NET Core now?

**Comment by dsyme** [comment]
@isaacabraham I don't think we're quite there yet.  The additions are of independent value however, as they means the correct code will be generated for a particular target .NET Framework version. The TP will now map the description of the provided types to the referenced set of binaries, looking for matching type names in the referenced assemblies.  

The things blocking .NET Standard/.NET Core are mostly described in 
* https://github.com/Microsoft/visualfsharp/issues/3303
