### ISSUE TITLE
Debug / callstack on dotnet core?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.TypeProviders.SDK#151]
On Windows things seem to work well...

But on Mac and Ubuntu I get exception:

```
tuomas$ fsharpi --debug

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "/usr/local/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/netstandard.dll";;

--> Referenced '/usr/local/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/netstandard.dll' (file may be locked by F# Interactive process)

> #r "../../../bin/netstandard2.0/FSharp.Data.SqlProvider.dll";;

  #r "../../../bin/netstandard2.0/FSharp.Data.SqlProvider.dll"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/Users/tuomas/myfolder/stdin(3,1): error FS3033: 
   The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: 
      The method or operation is not implemented.
```

Ok, I don't know what method. Is there any way to get more information?
I would like to see compiler stack-trace (or some debugging possibility for compilation time). Currently I have found the only way to echo anything is to insert `failwith` commands to source-code and remove them one-by-one, but the fsharp core compiler is so slow that it's not really productive option.

**Comment by zaaack** [comment]
Dlls output by dotnet core cannot be run in mono(fsharpi), and I get it worked in another issue. But it would help a lot if  this can be added to the readme.

**Comment by Thorium** [comment]
Got it, thanks. The only problem is if a type provider is referencing libraries that have different API on .NET Framework (Mono) and .NET Core. Then the compile time types are not compatible with runtime files. Well, this has been a problem of .NET binding-redirects already so I guess it's a design decision that we have to deal with.
