### ISSUE TITLE
Assembly is referenced but not appearing in translation set

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.TypeProviders.SDK#173]
See https://github.com/fsprojects/FsXaml/issues/73#issuecomment-338833437

**Comment by piaste** [comment]
Data point: the same error occurs in property setters (but not getters) for SQLProvider, when the mapped CLR types come from a database library (e.g. Npgsql).

**Comment by dsyme** [comment]
@ReedCopsey @piaste I have a proposed fix for this in https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/187

**Comment by dsyme** [comment]
@ReedCopsey @piaste @Thorium the fix for this issue is now merged, thanks
