### ISSUE TITLE
mandatory invokeCode parameter in ProvidedMethod ctor senseless for statically parametrized TP methods  

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.SDK#180]
### Description

A new ProvidedTypes api is great but I wonder what is supposed to be passed as value for ```invokeCode``` https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/33fd1c0a95dd1ddfe77f12e4921b6983f72c8e62/src/ProvidedTypes.fsi#L96 parameter for  [statically parametrized TP methods](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.0/StaticMethodArgumentsDesignAndSpec.md).

### Known workarounds

For now I used bogus value ```Unchecked.defaultof<_>```
```fsharp
    let m = ProvidedMethod("CreateCommand", [], typeof<obj>, isStatic = true, invokeCode = Unchecked.defaultof<_>)
    m.DefineStaticParameters(staticParams, (fun methodName args ->
    ... 
```

**Comment by dsyme** [comment]
@dmitry-a-morozov Good point.  Yes, right now you need a bogus value.

**Comment by dsyme** [comment]
@dmitry-a-morozov We should also add test cases to statically parameterized methods to the TPSDK itself

**Comment by dmitry-a-morozov** [comment]
@dsyme I'll try to find time to add the test cases

**Comment by dsyme** [comment]
@dmitry-a-morozov I'll leave this open as we should make the parameter optional I suppose

**Comment by panesofglass** [comment]
I’ve made some progress making it optional and could submit a PR, if that is helpful.

**Comment by panesofglass** [comment]
I'm guessing your use case was for an erasing TP, as my attempt to do this for a generative TP resulted in a NRE.
