### ISSUE TITLE
add test cases to statically parameterized methods

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.SDK#181]

**Comment by dmitry-a-morozov** [comment]
@dsyme I'm thinking about submitting PR to close this issue.
Where do I put tests? BasicErasedProvisionTests.fs?

**Comment by dsyme** [comment]
That would be fantastic. Yes, BasicErasedProvisionTests.fs.


The current tests for static parameters of types uses the helpers in ProvidedTypesTesting.fs but they aren't particularly magical

**Comment by dsyme** [comment]
Closing this as a lot of testing has been added since then
