### ISSUE TITLE
Type provider packages/namespaces naming guidelines

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.SDK#198]
It would be nice to have  naming guidelines for type provider packages and namespaces.
Especially when a type provider provider library is a wrapper around existing .NET api like 

System.Data.SqlClient -> ???
Npgsql -> ???
Microsoft.EntityFrameworkCore.SqlServer -> ???

**Comment by dsyme** [comment]
@dmitry-a-morozov I'm ok to keep this open.  I spent a while thinking about TP naming around 2013 when we finalized F# 3.1, but I haven't revisited the issue for a while, and the packaging/naming guidelines don't say anything besides

> Likewise, a type provider for a data source or schema format XYZ should normally be placed in “FSharp.Data”, e.g. “FSharp.Data.XYZ”.

I'd be very happy to get at least the common examples added to the guidelines for people to have something to follow

**Comment by dsyme** [comment]
I added some notes in the README.md, thanks
