### ISSUE TITLE
Testing types are internal and need to be source included in the place you want to use them

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.TypeProviders.SDK#222]
### Description

Testing types are internal and need to be source included in the place you want to use them

### Repro steps

Try using the Testing types from your testing assembly

### Expected behavior

You should be able to instantiate testing types without having to source include the sdk in more than one assembly

### Actual behavior

You have to source include in more than one assembly, this can pose issues such as the same type existing in more than one assembly

### Known workarounds

Copy and paste parts of the code.

Fix is easy remove internal from ProvidedTypesTesting and its static members.

**Comment by dsyme** [comment]
After #228 ProvidedTypesTesting.fs should only be included in your test assembly, and not int he type provider itself.

`Testing` is made internal again though it doesn't really matter if it's internal or not

**Comment by 7sharp9** [comment]
Hmm, well I guess I need to fork then :-(
