### ISSUE TITLE
link broken in readme file

### ISSUE THREAD

**Issue by jkone27** [fsprojects/FSharp.TypeProviders.SDK#224]
### Description
In Readme.MD, section The ProvidedTypes API - Adding the Files, second link reported as ["this"](https://github.com/dsyme/FSharp.Data/blob/e841dde62091a82225b91b2f38b76513dafbfc05/src/FSharp.Data.Source.fsproj#L54-L59) to provide example on how to import files in project, is broken, giving 404.

### Repro steps

click on documentation link : https://github.com/dsyme/FSharp.Data/blob/e841dde62091a82225b91b2f38b76513dafbfc05/src/FSharp.Data.Source.fsproj#L54-L59

### Expected behavior

access the page.

### Actual behavior

github 404.

**Comment by dsyme** [comment]
Thanks, fixed
