### ISSUE TITLE
Custom Type provider doesn't work with FSharp.Core 4.5

### ISSUE THREAD

**Issue by francotiveron** [fsprojects/FSharp.TypeProviders.SDK#235]
### Description

I have a custom type provider, working correctly with FSharp.Core 4.3.4

### Repro steps

I upgrade FSharp.Core to 4.5.0 by nuget

### Expected behavior

The type provider continues to work as before

### Actual behavior

Type provider doesn't work anymore. When debugging, the type provider constructor is never called.

### Known workarounds

Downgrade to FSharp,Core 4.3.4

### Related information 

Operating system W10
.NET Framework 4.5
Visual Studio 2017 15.8.0 Preview 2.0

**Comment by sergey-tihon** [comment]
@francotiveron do you compile TP with FSharp.Core 4.5 or compile project that uses TP using FSharp.Core 4.5 ?

**Comment by francotiveron** [comment]
both

**Comment by dsyme** [comment]
@francotiveron In which design-time tool are you seeing the failure? Choose any or all of:
*  `devenv.exe` (if so which exact version please)
* `fsc.exe`  (if so which exact version please)
* `fsi.exe` (if so which exact version please)
* JetBrains Rider
* VSCode (fsautocomplete.exe)
* some other tool(s)

It could well be that one or more of these does not have the correct binding redirect to allow a TP requiring FSharp.Core 4.5 at design-time to work.

**Comment by francotiveron** [comment]
@dsyme I am using Visual Studio (devenv.exe)

![image](https://user-images.githubusercontent.com/8280970/41489738-5d248302-7134-11e8-9e06-c8e2f464d007.png)


Microsoft Visual Studio Community 2017 Preview
Version 15.8.0 Preview 2.0
VisualStudio.15.Preview/15.8.0-pre.2.0+27729.1
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA974
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10511.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.02025.0
ASP.NET and Web Tools 2017

ASP.NET Core Blazor Language Services   0.4.0-rtm-10319

ASP.NET Core Razor Language Services   15.8.31546
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.02027.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.5
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.8.02027.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.5
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.9.0-beta4-62923-05. Commit Hash: a5e9a61f37a0dfafb5069f4ab104d6d5d909423c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.5.2.2566
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

Merq   1.1.38 (5b3c069)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.3000.5
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.5
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.2
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.5
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10510.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.27709.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.8.20517.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta4-62923-05. Commit Hash: a5e9a61f37a0dfafb5069f4ab104d6d5d909423c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.8.0.0.  Commit Hash: 8f54b635fe6bf248b2462b8b400a93264b912927.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.11.0.510 (61e65abd2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.13.604 (8ebc70fc1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.99.12 (HEAD/de662f58d)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.11.0.313 (0416ea0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dsyme** [comment]
@francotiveron I think we need more specific repro steps.  Could you create a "clean" repro of this with step by step instructions?  Many thanks

**Comment by dsyme** [comment]
Closing this old issue
