### ISSUE TITLE
how to make a static ctor in generative providers?

### ISSUE THREAD

**Issue by giacomociti** [fsprojects/FSharp.TypeProviders.SDK#246]
I'm trying to add a static constructor in a generative type provider:

    let addStaticCtor (providedType: ProvidedTypeDefinition) =
        let ctor = ProvidedConstructor([], invokeCode = fun _ -> <@@ printfn "hello" @@>)
        ctor.IsTypeInitializer <- true
        providedType.AddMember ctor
    
but the constructor is not generated. Is this the intended way to do it?

In previous versions, it was allowed to first specify the flag (`IsTypeInitializer=true`) and then setting the `InvokeCode` property, see for example [this type provider](https://github.com/rspeele/Rezoom.SQL/blob/master/src/Rezoom.SQL.Provider/TypeGeneration.fs#L373).

What am I missing?

**Comment by dsyme** [comment]
Looks like missing functionality, will add it now

**Comment by giacomociti** [comment]
Thanks!
