### ISSUE TITLE
Simplifying things by moving to VisualFSharp

### ISSUE THREAD

**Issue by cartermp** [fsprojects/FSharp.TypeProviders.SDK#248]
Things like this seem awfully unnecessary if the SDK were a part of the VisualFSharp repo and built with our tasks and targets: https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/fsc.props

Would it be preferable for this to be brought into VisualFSharp? We already build a type provider that we run through CI with the Type Provider SDK.

**Comment by dsyme** [comment]
> Things like this seem awfully unnecessary if the SDK were a part of the VisualFSharp repo and built with our tasks and targets: https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/fsc.props

I think that file is now redundant now that .NET SDK F# compilers support type providers, e.g. see the comment at the top: https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/fsc.props#L3

It's plausible we could/should move the TPSDK into "visualfsharp" but not for that particular reason.  However "visualfsharp" is already too big as a repo (especially the inclusion of vsintegration and VS setup) and still has a strong bias towards Visual Studio/Windows engineering issues.   Those are very important and it's crucial to keep focus on those.   At the moment I am loathe to increase the scope of what gets engineered there - we would trade one kind of efficiency for another.

**Comment by cartermp** [comment]
Makes sense.
