### ISSUE TITLE
Changed location of F# SDK in Visual Studio 15.8 leads to compilation errors

### ISSUE THREAD

**Issue by bartsokol** [fsprojects/FSharp.TypeProviders.SDK#249]
### Description

In Visual Studio version 15.8 F# SDK was moved inside the installation directory of the VS, so the paths provided [in the `fsc.props` file](https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/fsc.props) don't point to SDK any more. Thus solving [issue with type providers and .NET Core SDK decribed here](https://github.com/Microsoft/visualfsharp/issues/3303) requires adding new paths.

One problem is that now the path is dependent on the variant of the VS installed (Community vs Professional vs...), so there needs to be a path added for each variant in use.

### Repro steps

* Install Visual Studio 2017 version 15.8 on your machine, without having separate F# SDK installed
* Try to compile the code using type providers (in my case it was Swagger Provider) using `dotnet` CLI

### Expected behavior

Code compiles.

### Actual behavior

Compilation ends with error.

### Known workarounds

Put new path to SDK in local props file (e.g. `Directory.build.props`) for all variants of Visual Studio that are in use in your organization. For Community variant it would be:

```
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
```

### Related information 

* Windows 10
* Visual Studio 15.8, .NET Core SDK 2.1.400

**Comment by dsyme** [comment]
Fixed in fsc.props
