### ISSUE TITLE
Full Custom Attributes for ProvidedProperty is not implemented

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.TypeProviders.SDK#288]
I guess this is by design, I have added an impl here: 

https://github.com/7sharp9/FSharp.TypeProviders.SDK/commit/5237ee5bbff10e1699b7b27e009dd0d34018119

Do you want a PR?

**Comment by dsyme** [comment]
Yes please

**Comment by 7sharp9** [comment]
Implementation is still above, forgotten the code now so closing.
