### ISSUE TITLE
Question: Reference to deprecated preview of NETStandard.Library.NETFramework in the Readme?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.TypeProviders.SDK#296]
The Readme.md tells the user reference to `NETStandard.Library.NETFramework` at [Making a .NET Standard 2.0 TPDTC](https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/README.md#making-a-net-standard-20-tpdtc). This also comes with the LemonadeProvider template.

However, NuGet package of [NETStandard.Library.NETFramework](https://www.nuget.org/packages/NETStandard.Library.NETFramework/2.0.0-preview2-25405-01) contains only non-stable version available, and the package states:

> This package is deprecated. To consume .NET Standard libraries from .NET Framework in VS2017 15.3, you only need the .NET Core 2.0 SDK installed.

So my question is that should I rather include a netstandard.dll from my installed frameworks `C:\Program Files\dotnet\sdk\` to the NuGet package, and which version? 
At least `2.1.202\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\` seems to work?

**Comment by Thorium** [comment]
The answer seems to be yes, you can update the dll, but then your TypeProvider won't work anymore.

**Comment by dsyme** [comment]
We should fix this - my understanding is that adding a `netstandard.dll` to your TPDTC will basically no longer be needed

Are you using a separated TPDTC like we discussed at F# Exchange?

**Comment by dsyme** [comment]
This has been removed a while back
