### ISSUE TITLE
Attempting to implement a Provided record

### ISSUE THREAD

**Issue by chkeita** [fsprojects/FSharp.TypeProviders.SDK#319]
# Attempting to implement a Provided record

I am trying to implement a providedRecord for a type provider i a working on.
My approach was to decompile a normal record and try to implement the methods and attributes present in the decompiled class.
I used the [decompiled](https://github.com/chkeita/AiqlTypeProvider/blob/e4bee45528b36dfa7bc5f0a2215006f1c9b5fd08/testing/Misc/MyRecordType.cs) code of this record as a template 
```F#
    type MyRecordType = {
        Dummy1: string
        Dummy2: int
    }
```
here is the definition of the [ProvidedRecord](https://github.com/chkeita/AiqlTypeProvider/blob/e4bee45528b36dfa7bc5f0a2215006f1c9b5fd08/AiqlTypeProvider/ProvidedTypeExtensions.fs#L58) and an example of [instantiation](https://github.com/chkeita/AiqlTypeProvider/blob/e4bee45528b36dfa7bc5f0a2215006f1c9b5fd08/AiqlTypeProvider/TestTypeProvider.fs#L8)  in a test Type Provider.
and here is an [example](https://github.com/chkeita/AiqlTypeProvider/blob/e4bee45528b36dfa7bc5f0a2215006f1c9b5fd08/testing/ConsoleApplication1/SampleApp/Program.fs#L36) of usage of that provider (reproduced here)
``` F#
type TestType = TestProvider.TestMainType<blah="demo">

let testRecordType () =
    FSharp.Reflection.FSharpType.IsRecord(typeof<TestType>)
    |> printfn "%A" 
    //=> true

    let test1 = TestType("", 1)
    printfn "%A" test1 
    //=> {prop1 = "";
    //=> prop2 = 1;}

    // This line does not compile 
    // error : The field, constructor or member 'prop1' is not defined
    // {TestType.prop1 = ""; TestType.prop2 = 1}
```
- I can check via reflection that the type is a record
- I can print the type and it looks like a record
- But I can only create the type via the public constructor (not available for normal record)
  I get an error when i try to use the record constructor (see code above)

What else do i need to do to have my type behave like a real record ?
Is it possible to implement a ProvidedRecord with this approach?

**Comment by dsyme** [comment]
> Is it possible to implement a ProvidedRecord with this approach?

Not with this alone

> What else do i need to do to have my type behave like a real record ?

You would need to modify the F# compiler (particularly `infos.fs`) to understand the compiled version of records as actual records.

**Comment by chkeita** [comment]
I think i have a working version of the [changes needed for intellisense](https://github.com/chkeita/fsharp/commit/2187a359a85230a7fbb74f497bcecf83bdc62b34) to work properly.
However i am getting an exception when accessing the field at runtime.
> Attempt by method 'Program.testRecordType()' to access field 'Program+TestType.prop1@' failed.

it looks like the compiler is accessing the backing field **prop1@** instead of the public property **prop1**

My guess is that i am missing a couple of attribute on the internal field that i generate in the type provider. Unfortunately, i can't reflect on the backing field of real record type to find out what are the expected attributes. 

Any pointers for how to solve this issue ?

**Comment by chkeita** [comment]
The backing fields were supposed **internal** instead of **private**
