### ISSUE TITLE
Doesn't work with F# 4.7

### ISSUE THREAD

**Issue by haf** [fsprojects/FSharp.TypeProviders.SDK#320]
### Description

https://github.com/dotnet/fsharp/issues/7470

https://github.com/haf/fsharp-tp-4.7-repro

Cross posing since it may be about msbuild rules from this repo.

**Comment by jackfoxy** [comment]
Could be related to this?
https://github.com/fsprojects/FSharp.Data.SqlClient/issues/361

Although this problem is specifically with netstandard2.1

**Comment by haf** [comment]
@jack-pappas Thank you for your reply; the cross-post told the story — you can't vary the version of the F# compiler from that of the SDK's, hence you can't use later versions of the compiler via later versions of F# Core, on an old SDK.
