### ISSUE TITLE
Support for netcoreapp3.x

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.TypeProviders.SDK#328]
The type provider template has support for netstandard2.0 and netcoreapp2.0. It would be good to move to netcoreapp3.0 as well.

**Comment by realvictorprm** [comment]
That early?

Isaac Abraham <notifications@github.com> schrieb am So., 22. Dez. 2019,
16:19:

**Comment by sergey-tihon** [comment]
Why do no think that it is early?
I guess it means 3.1 only for design time component, that is LTS and will be supported till ~2022.
With MS recommendation uses latest SDK, I believe most of people who use .net core already has 3.1 installed.

**Comment by sergey-tihon** [comment]
@isaacabraham new template is release (v6.0.0). 
Can you please try it and confirm that it works for you too?

new steps
```
dotnet new --install FSharp.TypeProviders.Templates::6.0.0
dotnet new typeprovider -n LemonadeProvider

cd LemonadeProvider

dotnet tool restore
dotnet paket update
dotnet build -c release

dotnet test -c release

dotnet paket pack nuget --version 0.0.1
```

**Comment by isaacabraham** [comment]
Will do. If it works I might consider porting the Azure Storage TP over to it - currently that project is basically blocked.

**Comment by sergey-tihon** [comment]
@isaacabraham does it work for you?

**Comment by dsyme** [comment]
Fixed now (testing is net5.0, TP is netstandard2.1)
