### ISSUE TITLE
Publish new FSharp.TypeProviders.Templates

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/FSharp.TypeProviders.SDK#361]
### Description

After the merge of https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/347, https://www.nuget.org/packages/FSharp.TypeProviders.Templates/ should have a new version published.

### Repro steps

https://www.nuget.org/packages/FSharp.TypeProviders.Templates/ is out of date.

### Expected behavior

It's up-to-date.

### Actual behavior

It's out-of-date.

### Known workarounds

Downloading directly.

**Comment by dsyme** [comment]
Thanks, I've marked it as a todo in my inbox
