### ISSUE TITLE
Start improving the ProvidedTypes API

### ISSUE THREAD

**Issue by mavnn** [fsprojects/FSharp.TypeProviders.SDK#38]
It would be nice to start including things like Colin's [quotation helpers](http://colinbul.wordpress.com/2014/07/20/type-providers-record-union-types-and-constant-type-unsupported/) and @tpetricek 's [curried func builder](http://stackoverflow.com/a/23375794/68457) into this package some how.

Should we be adding more code files? Amending ProvidedTypes? I'd like some more functional wrappers around things like adding methods to types as well.

@dsyme @ovatsus @7sharp9 thoughts?

**Comment by dsyme** [comment]
Closing this old issue
