### ISSUE TITLE
Question about intellisense being broken with .<Note>

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.TypeProviders.SDK#390]
This is a bit long shot, but do you know why a TypeProvider intellisense is broken after Visual Studio 2022 version upgrade to 17.3.x?

![image](https://user-images.githubusercontent.com/229355/196897226-ab1a1b46-c34c-4826-b23f-362c196de4fd.png)

It wants some reference to Windows 255.255.255.255, what is that dll, never heard? Which NuGet package is that from?

Or could this be a problem with `Task` type handling in ProvidedTypes.fs?

**Comment by dsyme** [comment]
@Thorium Please list a full repro - which type provider, what dependencies it has and so on

**Comment by Thorium** [comment]
I thought it would be nice to know if other people have similar problems and in which conditions.
Google search doesn't expose a lot.

This was .NET Framework full, loaded SQLProvider (SSDT, no real database connection, just flat file parsing). I have also loaded FSharp.Data (with a few non-small xmls) and as far as I know, either of those are not having Nuget package references on .NET full (except maybe to FSharp.Core) or any referencing to a "Windows" anything. 

The intellisense did work on VS2019 very well (maybe survivorship bias on my memories), but VS2022 it sometimes does, sometimes not. I don't know if this is related:
![image](https://user-images.githubusercontent.com/229355/198298104-0f233575-bc6e-4d63-b19c-395baf37151a.png)

That's why my initial suspects were:
- ProvidedTypes.fs is always a good suspect.
- Tasks, as maybe new versions expose accidentally some task to intellisense and F# doesn't await.
- Or VS2022 itself, the Windows.dll sounds something very UI related

Compile time the code works, and runs, it's just intellisense that is broken.

**Comment by Thorium** [comment]
One thing that might be related: I was running VS on Windows 10 in non-admin mode. As typically every VS update resets the short-cut back to non-admin permissions.

**Comment by Thorium** [comment]
Ok I think the intellisense being broken is not actually TypeProvider-issue as such (except type-providers can probe runtime assemblies), but this: https://github.com/dotnet/fsharp/issues/9206

Definitely I got the whole compiler to crash to this error (not only intellisense), when I tried to use a C# library returning me a ValueTask<bool>

**Comment by Thorium** [comment]
I think I found the issue.
The TypeProvider had a reference to `System.Net.Http` which has dependency to `System.Runtime.WindowsRuntime` which is the poisonous dll referred also above. 

Causing that to load on the design-time dll, somehow conflicted with something, causing this error. The solution, that seems to work so far, was to restrict the System.Net.Http reference target frameworks, as it has that dependency only on one of the target frameworks it has: https://www.nuget.org/packages/System.Net.Http#dependencies-body-tab
