### ISSUE TITLE
Add filesystem watcher invalidation code

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/FSharp.TypeProviders.SDK#6]
This is something that is tricky to get right, and it's common across many projects. Maybe we should add it here so people have a stable reference implementation

See
https://github.com/fsharp/fsharpx/issues/268
https://github.com/fsharp/FSharp.Data/issues/236
https://github.com/forki/FSharp.Management/pull/13
https://github.com/fsharp/FSharp.Data/pull/283
https://github.com/fsharp/FSharp.Data/pull/286
https://github.com/fsharp/FSharp.Data/pull/287

/cc @vasily-kirichenko @forki @tpetricek

**Comment by dsyme** [comment]
Closing this old issue
