### ISSUE TITLE
Include samples/tests from old f# sample pack

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.SDK#66]
[F# sample pack](http://fsharp3sample.codeplex.com/) used to have VERY IMPORTANT set of samples + tests. 

Samples
http://fsharp3sample.codeplex.com/SourceControl/latest#SampleProviders/Samples.Tests/TypeProviders/TypeProviders.fs
Tests
http://fsharp3sample.codeplex.com/SourceControl/latest#SampleProviders/Samples.Tests/Clients/Clients.fs

Personally for me it test suit was live saver during type providers developments.
I think it makes sense to include it into this repository. And of course maintain it.

**Comment by dsyme** [comment]
Closing this old issue
