### ISSUE TITLE
Struct as ProvidedTypeDefinition

### ISSUE THREAD

**Issue by buybackoff** [fsprojects/FSharp.TypeProviders.SDK#77]
At my very first attempt to create a ProvidedTypeDefinition I used the following line:

```
let mTy = ProvidedTypeDefinition(message.Key, baseType = Some(typeof<ValueType>), 
                            HideObjectMethods = true, IsErased = false)
```

The TP and code gen worked with `ValueType` until I called constructor of the provided type. Then I received a CLR error saying about stack corruption.

When I compared IL of my provided value type with a normal struct constructor I found some differences. IL_0001 calls ValueType constructor, but it shouldn't be done for structs. It seems that it is possible to add special handling of ValueTypes on [this line](https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/eb919461a3cfc5bd8a7569a7af723566b678e8fa/src/ProvidedTypes.fs#L2395) (and maybe somewhere else) and generate valid constructors. 

I am not yet comfortable with IL. What is needed to generate structs if that is possible at all?

```
.method public specialname rtspecialname 
    instance void .ctor (
        class [Spreads.Extensions]Spreads.Serialization.IDirectBuffer buffer
    ) cil managed 
{
    // Method begins at RVA 0x20d4
    // Code size 31 (0x1f)
    .maxstack 4
    .locals init (
        [0] valuetype SBETypeProviderTest.CarSchema/Car,
        [1] class [Spreads.Extensions]Spreads.Serialization.IDirectBuffer
    )

    IL_0000: ldarg.0
    IL_0001: call instance void [mscorlib]System.ValueType::.ctor()
    IL_0006: ldarg.0
    IL_0007: nop
    IL_0008: nop
    IL_0009: stloc.0
    IL_000a: nop
    IL_000b: nop
    IL_000c: ldarg.1
    IL_000d: nop
    IL_000e: nop
    IL_000f: stloc.1
    IL_0010: nop
    IL_0011: nop
    IL_0012: ldloca.s 0
    IL_0014: nop
    IL_0015: nop
    IL_0016: ldloc.1
    IL_0017: nop
    IL_0018: nop
    IL_0019: stfld class [Spreads.Extensions]Spreads.Serialization.IDirectBuffer SBETypeProviderTest.CarSchema/Car::_directBuffer
    IL_001e: ret
} // end of method Car::.ctor
```

**Comment by buybackoff** [comment]
I was able to create a struct with the following changes and setting IsImplicit <- true. However, with implicit I cannot access fields from ProvidedProperties.

```
                | None ->  
                    if ptd.BaseType = typeof<ValueType> then
                      () // do nothing
                    else
                      ilg.Emit(OpCodes.Ldarg_0)
                      let cinfo = ptd.BaseType.GetConstructor(BindingFlags.Public ||| BindingFlags.NonPublic ||| BindingFlags.Instance, null, [| |], null)
                      ilg.Emit(OpCodes.Call,cinfo)
                | Some f -> 
                    // argExprs should always include 'this'
                    let (cinfo,argExprs) = f (Array.toList parameters)
                    for argExpr in argExprs do 
                        emitExpr (ilg, locals, parameterVars) ExpectedStackState.Value argExpr
                    ilg.Emit(OpCodes.Call,cinfo)
                
//                if ptd.BaseType = typeof<ValueType> then
//                  () // here we should call Invoke expression without locals
//                el
                if pcinfo.IsImplicitCtor then
                    for ctorArgsAsFieldIdx,ctorArgsAsField in List.mapi (fun i x -> (i,x)) implicitCtorArgsAsFields do 
                        ilg.Emit(OpCodes.Ldarg_0)
                        ilg.Emit(OpCodes.Ldarg, ctorArgsAsFieldIdx+1)
                        ilg.Emit(OpCodes.Stfld, ctorArgsAsField)
                else
                    let code  = pcinfo.GetInvokeCodeInternal true
                    let code = code parameters
                    emitExpr (ilg, locals, parameterVars) ExpectedStackState.Empty code
                ilg.Emit(OpCodes.Ret)
```

Haven't figured out how to avoid creating locals but still calling the `code` part on this line: `emitExpr (ilg, locals, parameterVars) ExpectedStackState.Empty code`. With this change structs should work normally.

**Comment by mavnn** [comment]
@buybackoff I must admit I have almost no knowledge of the il generation side of things at all. Maybe @dsyme or @tpetricek can help, or at least tell us who might be able to.

**Comment by buybackoff** [comment]
@mavnn my problem here is quotations more than IL - how to emit IL from `GetBaseConstructorCallInternal` or single the `code` Expression. Empty array instead of `parameterVars` didn't work.

**Comment by sergey-tihon** [comment]
Should it work at all? I thought that TP could not provide structs as well as records and discriminated unions.

**Comment by buybackoff** [comment]
As I said, I was able to generate one with very limited functionality. As far as I understand, Type Providers are just an interactive extension to the compiler, so why not to generate anything the compiler or IL.Emit can!?

**Comment by buybackoff** [comment]
@dsyme @tpetricek should that be feasible at all? I feel like doing this, unless there is some unknown for me blocking issue that I will learn in the process.

**Comment by dsyme** [comment]
This was done here: https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/344
