### ISSUE TITLE
How to create generative providers with the new context based provided type API without error.

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.TypeProviders.SDK#82]
Currently if I convert to the new API I get a:
![](https://i.imgur.com/fabH3BS.png)

Which seems to stem from assembly generator:

``` fsharp
type ProvidedAssembly(assemblyFileName: string) = 
    let theTypes = ResizeArray<_>()
    let assemblyGenerator = AssemblyGenerator(assemblyFileName)
    let assemblyLazy = 
        lazy 
            assemblyGenerator.Generate(theTypes |> Seq.toList)
```

If would be great if the provided types API was able to support unchecked quotation for generative types as they have the same issues relating to reflection based loading etc.

**Comment by 7sharp9** [comment]
@dsyme Any advice on getting this to work on generative would be greatly received :-)

**Comment by dsyme** [comment]
@7sharp9 Can you give a detailed repro for this please, with a link to a sample project or PR, and details of operating system etc.?

**Comment by 7sharp9** [comment]
I don't currently have a public repro but Ill see about making one.

**Comment by 7sharp9** [comment]
Ok, repro repo is here:
https://github.com/7sharp9/ContextBasedGenerative

![Error](https://i.imgur.com/rw3SVzF.png)

This code used to work fine before using the ctxt to add the various provided entities.

I used the very lasted code that was committed here this morning.

**Comment by sergey-tihon** [comment]
@7sharp9 Could you please add this as a test to this repo?
Seems like I also need working sample of this.

**Comment by 7sharp9** [comment]
@sergey-tihon Thats the thing, it doesn't work at all yet for generatives.

**Comment by 7sharp9** [comment]
Ok this has been here for a year now, is the context API going to be the way forward or forever experimental?  //cc @dsyme

**Comment by AviAvni** [comment]
@7sharp9 @dsyme I debugged the repro what I found is that when using types like ```obj``` or ```string``` as base type like in
https://github.com/7sharp9/ContextBasedGenerative/blob/master/ContextBasedGenerative/TypeProvider.fs#L20

then this type is converted using this function:
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypesContext.fs#L149
to ContextTypeDefinition that not implement Module property and other type functionality.

when I changed the implementation of replaceType to return the same type for types defined in mscorlib
then the code in the test compiled and work correctly

then I tried to understand why this convert is needed for types that is not provided types still didn't understand why it's needed

I tried also to make the base type of the provider a type that i decleared in the ContextBasedGenerative
I had the same problem and when I changed this line:
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypesContext.fs#L175
to return ```t``` it also work in the test and the base type was correct one from the ContextBasedGenerative assembly

this is the summary for what  I found till now
what do you think?
what I can do to help more?

**Comment by dsyme** [comment]
I've added a comment about this here https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/133#event-1282930241

I think we need to move to a different IL writer for generative providers authored using this SDK.  I'm quite keen to minimize binary dependencies, so I'm inclined to use the Abstract IL writer from the F# compiler, since it can be just a single file (like our assembly reader), but I need to think about it.

**Comment by AviAvni** [comment]
@dsyme can be close https://github.com/7sharp9/ContextBasedGenerative/pull/1

**Comment by dsyme** [comment]
@AviAvni Thanks, this is fixed through the updated SDK
